# Generated by Django 6.0.3 on 2026-07-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyContractSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_success', models.BooleanField(default=False)),
                ('bonus_type', models.CharField(blank=True, max_length=20)),
                ('success_bonus_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('success_bonus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('failure_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('driver_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner_pay', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_worked', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
            options={
                'unique_together': {('driver', 'year', 'month')},
            },
        ),
    ]
