# Generated by Django 6.0.7 on 2026-07-28 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('license_type', models.CharField(blank=True, max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('daily_quota_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_salary_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contract_target_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_success_bonus_fixed_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contract_success_bonus_percentage_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('contract_failure_percentage_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('portal_password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_portal_enabled', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='vehicles.vehicle')),
            ],
        ),
    ]
