# Generated by Django 6.0.7 on 2026-07-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
