# Generated by Django 6.0.7 on 2026-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_license_type'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='driver',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this driver'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['phone'], name='drivers_dri_phone_39e97b_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['vehicle', 'is_active'], name='drivers_dri_vehicle_0eab9f_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['driver_code'], name='drivers_dri_driver__0f4e25_idx'),
        ),
    ]
