# Generated by Django 6.0.7 on 2026-07-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_settlement_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
