# Generated by Django 6.0.3 on 2026-07-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_cap', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('repayment_percentage', models.IntegerField(default=100)),
                ('minimum_driver_take', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_name', models.CharField(default='My Transport Fleet', max_length=200)),
                ('company_phone', models.CharField(blank=True, max_length=20)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_address', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('days_in_month_for_salary', models.IntegerField(default=30)),
                ('contract_settlement_day', models.IntegerField(default=1, help_text='Day of month when contract is settled')),
                ('cash_alert_threshold', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('bank_alert_threshold', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbook.bankaccount')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
