# Generated by Django 6.0.3 on 2026-07-31 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cash in Hand',
                'verbose_name_plural': 'Cash in Hand',
            },
        ),
        migrations.CreateModel(
            name='DailyCashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('addition', 'Cash Addition'), ('withdrawal', 'Cash Withdrawal'), ('transfer_to_bank', 'Transfer to Bank'), ('transfer_from_bank', 'Transfer from Bank'), ('expense_cash', 'Expense (Cash)'), ('expense_bank', 'Expense (Bank)'), ('petty_cash', 'Petty Cash'), ('salary_payment', 'Salary Payment'), ('commission_payment', 'Commission Payment'), ('bonus_payment', 'Bonus Payment'), ('loan_repayment', 'Loan Repayment'), ('settlement_collection', 'Settlement Collection')], max_length=30)),
                ('category', models.CharField(choices=[('settlement_collection', 'Driver Settlement Collection'), ('other_income', 'Other Income'), ('loan_income', 'Loan Received'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance/Repairs'), ('insurance', 'Insurance'), ('permit', 'Permit/License'), ('admin_expense', 'Admin Expense'), ('driver_salary', 'Driver Salary'), ('driver_commission', 'Driver Commission'), ('driver_bonus', 'Driver Bonus'), ('repayment', 'Loan Repayment'), ('other_expense', 'Other Expense'), ('petty_cash_expense', 'Petty Cash Expense')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('cash_balance_after', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('bank_balance_after', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cashbook.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='settlements.dailysettlement')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
