# Generated by Django 6.0.7 on 2026-07-29 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settlements', '0003_dailysettlement_cash_added_to_hand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_additions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyCashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bank_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bank_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_settlement_collections', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vehicle_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_driver_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_business_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('addition', 'Addition to Cash'), ('withdrawal', 'Withdrawal from Cash'), ('transfer_to_bank', 'Transfer to Bank'), ('transfer_from_bank', 'Transfer from Bank'), ('expense', 'Business Expense'), ('petty_cash', 'Petty Cash')], max_length=20)),
                ('category', models.CharField(choices=[('settlement_collection', 'Driver Settlement Collection'), ('other_income', 'Other Income'), ('loan_income', 'Loan Received'), ('vehicle_expense', 'Vehicle Expense'), ('salary_payment', 'Driver Salary Payment'), ('commission_payment', 'Driver Commission Payment'), ('bonus_payment', 'Driver Bonus Payment'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance/Repairs'), ('insurance', 'Insurance'), ('permit', 'Permit/License'), ('loan_repayment', 'Loan Repayment'), ('admin_expense', 'Admin Expense'), ('other_expense', 'Other Expense')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('cash_in_hand_balance_after', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('bank_balance_after', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cashbook.bankaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='settlements.dailysettlement')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
