# Generated by Django 6.0.7 on 2026-08-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='category',
            field=models.CharField(choices=[('settlement_collection', 'Driver Settlement Collection'), ('other_income', 'Other Income'), ('loan_income', 'Loan Received'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance/Repairs'), ('insurance', 'Insurance'), ('permit', 'Permit/License'), ('admin_expense', 'Admin Expense'), ('driver_salary', 'Driver Salary'), ('driver_commission', 'Driver Commission'), ('driver_bonus', 'Driver Bonus'), ('repayment', 'Loan Repayment'), ('other_expense', 'Other Expense'), ('petty_cash_expense', 'Petty Cash Expense'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('loan_interest', 'Loan Interest')], max_length=30),
        ),
    ]
