# Generated by Django 6.0.7 on 2026-07-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashinhand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cashtransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='total_additions',
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='total_withdrawals',
        ),
        migrations.RemoveField(
            model_name='cashinhand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cashtransaction',
            name='cash_in_hand_balance_after',
        ),
        migrations.AddField(
            model_name='cashinhand',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashinhand',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='cash_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='category',
            field=models.CharField(choices=[('settlement_collection', 'Driver Settlement Collection'), ('other_income', 'Other Income'), ('loan_income', 'Loan Received'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance/Repairs'), ('insurance', 'Insurance'), ('permit', 'Permit/License'), ('admin_expense', 'Admin Expense'), ('driver_salary', 'Driver Salary'), ('driver_commission', 'Driver Commission'), ('driver_bonus', 'Driver Bonus'), ('repayment', 'Loan Repayment'), ('other_expense', 'Other Expense'), ('petty_cash_expense', 'Petty Cash Expense')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('addition', 'Cash Addition'), ('withdrawal', 'Cash Withdrawal'), ('transfer_to_bank', 'Transfer to Bank'), ('transfer_from_bank', 'Transfer from Bank'), ('expense_cash', 'Expense (Cash)'), ('expense_bank', 'Expense (Bank)'), ('petty_cash', 'Petty Cash'), ('salary_payment', 'Salary Payment'), ('commission_payment', 'Commission Payment'), ('bonus_payment', 'Bonus Payment'), ('loan_repayment', 'Loan Repayment'), ('settlement_collection', 'Settlement Collection')], max_length=30),
        ),
    ]
