# Generated by Django 6.0.7 on 2026-08-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0002_alter_cashtransaction_category'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='loans.loan'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='category',
            field=models.CharField(choices=[('settlement_collection', 'Driver Settlement Collection'), ('other_income', 'Other Income'), ('loan_income', 'Loan Received'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('loan_interest', 'Loan Interest'), ('fuel', 'Fuel'), ('maintenance', 'Maintenance/Repairs'), ('insurance', 'Insurance'), ('permit', 'Permit/License'), ('admin_expense', 'Admin Expense'), ('driver_salary', 'Driver Salary'), ('driver_commission', 'Driver Commission'), ('driver_bonus', 'Driver Bonus'), ('other_expense', 'Other Expense'), ('petty_cash_expense', 'Petty Cash Expense')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('addition', 'Cash Addition'), ('withdrawal', 'Cash Withdrawal'), ('transfer_to_bank', 'Transfer to Bank'), ('transfer_from_bank', 'Transfer from Bank'), ('expense_cash', 'Expense (Cash)'), ('expense_bank', 'Expense (Bank)'), ('petty_cash', 'Petty Cash'), ('salary_payment', 'Salary Payment'), ('commission_payment', 'Commission Payment'), ('bonus_payment', 'Bonus Payment'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('loan_interest', 'Loan Interest'), ('settlement_collection', 'Settlement Collection')], max_length=30),
        ),
    ]
