# Generated by Django 6.0.7 on 2026-07-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan (4-seater)'), ('minivan', 'Minivan (6-8 seater)'), ('minibus', 'Minibus (14-seater)'), ('bus', 'Bus (30-50 seater)')], max_length=20)),
                ('seats', models.PositiveIntegerField()),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('operating_model', models.CharField(choices=[('quota', 'Quota System'), ('salary', 'Monthly Salary'), ('percentage', 'Percentage System'), ('contract', 'Contract System')], default='quota', max_length=20)),
                ('daily_quota', models.DecimalField(decimal_places=2, default=250.0, help_text='Only used for quota model', max_digits=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=3000.0, help_text='Only used for salary model', max_digits=10)),
                ('driver_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text="Driver's percentage of gross income (e.g., 30%)", max_digits=5)),
                ('contract_target', models.DecimalField(decimal_places=2, default=15000.0, help_text='Monthly target gross income for contract model', max_digits=10)),
                ('contract_success_bonus_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Gross'), ('hybrid', 'Hybrid (Fixed + Percentage)')], default='fixed', help_text='Only used for contract model', max_length=20)),
                ('contract_success_bonus_fixed', models.DecimalField(decimal_places=2, default=2000.0, help_text='Fixed bonus amount if target achieved', max_digits=10)),
                ('contract_success_bonus_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage bonus if target achieved (e.g., 10%)', max_digits=5)),
                ('contract_failure_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage of gross income driver keeps if target is NOT achieved', max_digits=5)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('permit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loan_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
