# Generated by Django 6.0.7 on 2026-08-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0003_cashtransaction_loan_alter_cashtransaction_category_and_more'),
        ('loans', '0001_initial'),
        ('settlements', '0003_dailysettlement_loan_deduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaninterest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loanpayment',
            options={},
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashbook.bankaccount'),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlements.dailysettlement'),
        ),
    ]
