# Generated by Django 6.0.7 on 2026-07-28 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mobile_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toll_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('border_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('operating_model', models.CharField(choices=[('quota', 'Quota System'), ('salary', 'Monthly Salary'), ('percentage', 'Percentage System'), ('contract', 'Contract System')], editable=False, max_length=20)),
                ('daily_quota', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('surplus_shortfall', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('previous_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debt_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_debt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quota_paid_to_owner', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_salary_earned', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('monthly_salary_accumulated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('driver_percentage_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('owner_percentage_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_target', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_monthly_gross', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('contract_remaining_target', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('contract_driver_bonus', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_driver_failure_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_is_success', models.BooleanField(default=False, editable=False)),
                ('contract_bonus_type', models.CharField(default='', editable=False, max_length=20)),
                ('contract_success_bonus_fixed', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_success_bonus_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('contract_failure_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('contract_driver_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_owner_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('driver_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_owner_collected', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('ecocash', 'EcoCash'), ('card', 'Card'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('debt_status', models.CharField(choices=[('clear', 'Clear'), ('owing', 'Owing'), ('overdue', 'Overdue'), ('n/a', 'Not Applicable')], default='n/a', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('vehicle', 'driver', 'date')},
            },
        ),
    ]
