# Generated by Django 6.0.3 on 2026-07-31 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSettlementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('week_start_day', models.IntegerField(default=0, help_text='0=Monday, 6=Sunday')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='drivers.driver')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='DailySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_model', models.CharField(choices=[('quota', 'Quota System'), ('salary', 'Monthly Salary'), ('percentage', 'Percentage System'), ('contract', 'Contract System')], editable=False, max_length=20)),
                ('date', models.DateField(help_text='Primary date for this settlement')),
                ('settlement_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10)),
                ('week_start', models.DateField(blank=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mobile_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fuel_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maintenance_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('toll_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_expense_desc', models.CharField(blank=True, max_length=200)),
                ('driver_notes', models.TextField(blank=True)),
                ('owner_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('daily_quota', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('surplus_shortfall', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('debt_repaid', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('new_debt', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('quota_paid_to_owner', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('daily_salary_earned', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('monthly_salary_accumulated', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('driver_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('driver_percentage_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('owner_percentage_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_target', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_monthly_gross', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('contract_remaining_target', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('contract_driver_bonus', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_driver_failure_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_is_success', models.BooleanField(default=False, editable=False)),
                ('contract_bonus_type', models.CharField(blank=True, editable=False, max_length=20)),
                ('contract_success_bonus_fixed', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_success_bonus_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('contract_failure_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('contract_driver_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('contract_owner_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('driver_pay', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_owner_collected', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('debt_status', models.CharField(choices=[('none', 'No Debt'), ('accumulated', 'Debt Accumulated'), ('repaid', 'Debt Repaid'), ('partial', 'Partial Repayment')], default='none', editable=False, max_length=20)),
                ('cash_added_to_hand', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('cash_transaction_created', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['driver', 'date'], name='settlements_driver__c80d3b_idx'), models.Index(fields=['status', 'date'], name='settlements_status_48944b_idx')],
            },
        ),
    ]
