# Generated by Django 6.0.7 on 2026-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysettlement',
            name='debt_status',
            field=models.CharField(choices=[('none', 'No Debt'), ('accumulated', 'Debt Accumulated'), ('repaid', 'Debt Repaid'), ('partial', 'Partial Repayment'), ('overdue', 'Debt Cap Exceeded')], default='none', editable=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='DriverSettlementSchedule',
        ),
    ]
