# Generated by Django 6.0.7 on 2026-07-29 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_settlement_frequency'),
        ('settlements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysettlement',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='driver_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='owner_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='settlement_period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysettlement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailysettlement',
            name='operating_model',
            field=models.CharField(choices=[('quota', 'Quota System'), ('salary', 'Monthly Salary'), ('percentage', 'Percentage System'), ('contract', 'Contract System')], default='quota', editable=False, max_length=20),
        ),
        migrations.CreateModel(
            name='DriverSettlementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('week_start_day', models.IntegerField(default=0, help_text='0=Monday, 6=Sunday')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='drivers.driver')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
