# Generated by Django 6.0.7 on 2026-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0002_dailysettlement_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysettlement',
            name='cash_added_to_hand',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='cash_transaction_created',
            field=models.BooleanField(default=False),
        ),
    ]
