# Generated by Django 6.0.7 on 2026-08-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('settlements', '0002_alter_dailysettlement_debt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysettlement',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysettlement',
            name='loan_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_deductions', to='loans.loan'),
        ),
    ]
